[connections.gsheets]
type = "service_account"
project_id = "tu-n-uniform"
private_key_id = "35c4a3bdbf2f1a46b2bb6ab299e7292bc871fc33"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC6BtGK+1QbNLBa
oh//sR1keYACQ57dTpbnRV+tcEl8dovA8UkIqp3z+N+LGNAq2x1U1dZMJIcrpylt
jSDSHczIIrfuIS3leLRLsjIARlZazTX0IprLi1WDjubwuP3oUu9ls04//uiXAPXo
WB7ntOQC3VTn6tonlsXtGjp5dpjgbo2GxJlJOTOZ7ULRxCVhuk1oSR/YEfbcTiN5
aTC4dEdD1RWs6zm/acae+dBo/x+nqrF+rUnvLnhOmkjrirGm4ALo49z7AB+fsY7d
PKqEJgFlA7AiUjuzVuYejzLGApCWI36EUCX5LWCHju7nGfQnpXM8D34CZEhq75Gc
an0rSXFnAgMBAAECggEAPHxNE7CGd1YZZU7DssKm+O1cht/vvqt3+3ieFGmnKzXs
WO7bPVskgphQLw0BWn3mOphQ1m8mGDaBDOLPYiJYXFaVkXLuVmd50Ab/pQE5wMpq
mZfK1xXV1zHWuzybKjgVKO81KS+79qVUT5ifa91wKdJHciT1i9vFPUPC8Y1zRb19
yaRmwXECSG96tuetLvttLtw3X07k/58ocyKV2Smht3w2ix5ABn8ByFpDdUNdti+r
42wu/rqrw1YDGA7RcQG1j82+Ov1wP6BLrU4UsnOMQZhDFp1OG/gkFU+CS4ldu4Ur
P5dr7rty8gd1J2O9mOR9f7qKEFUeKdggIvBvbhT00QKBgQDyduXDnwRFprSxdp9M
OFE+TxHM6hjauxYeDBHI2G4SeI4yHIggtt3SqvOzhsNptyfBWdNHjYNYqV01c3Gu
ybO3Hyb2TvaUnag8fbHHMs+RILkxqsX+4zSYHbxfxD8MA41NiRhy4/P35fdxw9k2
V6hRgbpINxODIag1dpo4ridoXwKBgQDEaVu2WNc86SsZQBvAuuCCXdVlv65bYC5G
+Glg4tqMxNzIltpbKOxY+N1mkceTFMOkmcShxLOQNroraV61bPy9LeFl9d2O1uy5
u129jWES/ZuvuYKkVPFGsYambGnYJz7UmUw/qliEHOIwFWoUrQo1wIgN+3nsc40v
DzuhKxYz+QKBgQDe8PxrVveyo4pZ8tyeVNo/FK0lYcrgtE2t6yMfLgJn8XmuEhYJ
HpvwbUgPtsZPmh1v54whqrku+Ou/jhrlwIkCxB4rNIf+NsjOdjTVGJ9KrnAafw/3
QirGA/GFjQj7nvh6ZqiYW4mkU0umy5IaKZeW+lWyuRGz7WqhXiCIJXoOuQKBgQCy
q2kLcruxpCZZnPDiHN2YmgVCvuC8LL1MQDOUOCk5fuec7WWLIaoGsbSt1pUnHe9v
L5Yo1kfGO5KVZRALmC49ZZwx5Tv78VV9C42VniOdY+iZLPdDyCWH+nwTrnGGeQT1
3tH25F4LKD82IHTUhCjShub9WTMrPl5DXecPkKNs+QKBgQCZx0logLf2g7pZYjZW
kxmSwklCSlI1/m3pgzst8evzAH3jQoreQQ6KvP6Tld7spRrRR5040Kr4C8kBg66D
hSqYed9aDj+alhav0Fv52/G6f7izWvME2RSHFgsEuMil5eUPceFw85x0Yj8t2a8a
mzIVLh3it2aG2R+gSVBNuKZkJQ==
-----END PRIVATE KEY-----
"""
client_email = "tu-n-bot@tu-n-uniform.iam.gserviceaccount.com"
client_id = "111494860706041618879"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tu-n-bot%40tu-n-uniform.iam.gserviceaccount.com"
